name: 'Github Events To Feishu Bot Action'
description: 'send message to feishu bot'
author: 'junka + Samuka007'
inputs:
  webhook:
    description: 'feishu bot webhook url'
    required: true
  signkey:
    description: 'set when you enable signature verify'
    required: false
outputs:
  code:
    description: 'code from response'
runs:
  using: 'node20'
  main: 'dist/index.js'
